name: Terraform CI 

# whenever push any code into github repo, this yaml file will run 
on:
  pull_request:
    branches:
      - master

# declare the running agent (what VM to run?)
jobs: # what task u want it to run 
 terraform-ci: # can be called anything 
   runs-on: ubuntu-latest # docker image 

   steps:
  ##setup
   - name: Checkout repository
     uses: actions/checkout@v2 # uses - library in terraform

  #aws configure
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # or hardcode us-east-1

## install terraform (like installing binary)
   - name: Set up Terraform
     uses: hashicorp/setup-terraform@v1

#terraform init
   - name: Initialize Terraform
     run: terraform init # run - command line that we run on our own

#terraform fmt
   - name: Format Terraform
     run: terraform fmt

#terraform validate
   - name: validate Terraform
     run: terraform validate

#terraform plan
   - name: Terraform Plan
     run: terraform plan 